import os
import io
import json
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, HRFlowable,
    Table, TableStyle, ListFlowable, ListItem
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY

from app.agents.llm_client import query_llm, AGENT_PERSONAS
from app.services.state_manager import get_email_config


# ═══════════════════════════════════════════════════════════════════════════════
# EXPORT FORMATS: JSON & Markdown builders (for Export Button feature)
# ═══════════════════════════════════════════════════════════════════════════════

def build_json_report(
    prompt: str,
    final_answer: str,
    report_data: dict,
    confidence_score: int,
    debate_turns: list = None,
    consensus_claims: list = None,
    disputed_claims: list = None,
) -> str:
    """Build a structured JSON report for export."""
    report = {
        "report_metadata": {
            "generated_by": "AI Jury - 7-Agent Deliberation Pipeline",
            "generated_at": datetime.now().isoformat(),
            "confidence_score": confidence_score,
            "agent_count": 7,
        },
        "query": prompt,
        "executive_summary": report_data.get("executive_summary", ""),
        "key_findings": report_data.get("key_findings", []),
        "recommendations": report_data.get("recommendations", []),
        "sections": report_data.get("sections", []),
        "final_answer": final_answer,
        "claim_analysis": {
            "consensus_claims": consensus_claims or [],
            "disputed_claims": disputed_claims or [],
        },
        "agent_debate_turns": debate_turns or [],
    }
    return json.dumps(report, indent=2, default=str)


def build_markdown_report(
    prompt: str,
    final_answer: str,
    report_data: dict,
    confidence_score: int,
    debate_turns: list = None,
    consensus_claims: list = None,
    disputed_claims: list = None,
) -> str:
    """Build a formatted Markdown report for export."""
    lines = []
    lines.append("# AI Jury Report\n")
    lines.append(f"**Generated:** {datetime.now().strftime('%B %d, %Y at %H:%M UTC')}  \n")
    lines.append(f"**Confidence Score:** {confidence_score}%  \n")
    lines.append(f"**Pipeline:** 7-Agent Deliberation\n")
    lines.append("---\n")

    lines.append(f"## Query\n\n> {prompt}\n")
    lines.append("---\n")

    exec_summary = report_data.get("executive_summary", "")
    if exec_summary:
        lines.append(f"## Executive Summary\n\n{exec_summary}\n")
        lines.append("---\n")

    lines.append("## Final Synthesized Answer\n\n")
    lines.append(final_answer)
    lines.append("\n---\n")

    findings = report_data.get("key_findings", [])
    if findings:
        lines.append("## Key Findings\n")
        for f in findings:
            lines.append(f"- {f}")
        lines.append("\n---\n")

    recs = report_data.get("recommendations", [])
    if recs:
        lines.append("## Recommendations\n")
        for r in recs:
            lines.append(f"- {r}")
        lines.append("\n---\n")

    if consensus_claims:
        lines.append("## Consensus Claims\n")
        for c in consensus_claims:
            claim_text = c.get("claim", c) if isinstance(c, dict) else str(c)
            lines.append(f"- {claim_text}")
        lines.append("\n")

    if disputed_claims:
        lines.append("## Disputed Claims\n")
        for d in disputed_claims:
            claim_text = d.get("claim", d) if isinstance(d, dict) else str(d)
            evidence = d.get("evidence", "") if isinstance(d, dict) else ""
            lines.append(f"- {claim_text}")
            if evidence:
                lines.append(f"  - *Evidence: {evidence[:200]}*")
        lines.append("\n")

    if debate_turns:
        lines.append("## Agent Deliberation Transcript\n")
        for turn in debate_turns:
            t = turn if isinstance(turn, dict) else turn.dict() if hasattr(turn, 'dict') else str(turn)
            speaker = t.get("speaker_persona", "Agent")
            target = t.get("target_persona", "")
            arg = t.get("argument", "")
            header = f"### Turn {t.get('turn_number', '')}: {speaker}"
            if target:
                header += f" -> {target}"
            lines.append(header)
            lines.append(f"\n{arg}\n")

    lines.append("\n---\n")
    lines.append(f"*Generated by AI Jury 7-Agent LangGraph Pipeline*")

    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════════════
# PDF Generation
# ═══════════════════════════════════════════════════════════════════════════════

def _build_pdf(
    prompt: str,
    final_answer: str,
    report_data: dict,
    confidence_score: int,
    debate_turns: list = None,
    consensus_claims: list = None,
    disputed_claims: list = None,
) -> bytes:
    """Builds a professional multi-page PDF report and returns it as bytes."""

    buffer = io.BytesIO()
    debate_turns = debate_turns or []
    consensus_claims = consensus_claims or []
    disputed_claims = disputed_claims or []

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
    )

    # Colour palette
    PURPLE   = colors.HexColor("#8b5cf6")
    BLUE     = colors.HexColor("#3b82f6")
    GREEN    = colors.HexColor("#10b981")
    AMBER    = colors.HexColor("#f59e0b")
    RED      = colors.HexColor("#ef4444")
    SURFACE  = colors.HexColor("#18181b")
    BORDER   = colors.HexColor("#27272a")
    LIGHT    = colors.HexColor("#f4f4f5")
    MUTED    = colors.HexColor("#a1a1aa")

    base = getSampleStyleSheet()

    def _style(name, parent="Normal", **kw):
        return ParagraphStyle(name, parent=base[parent], **kw)

    h1_style     = _style("H1",       fontSize=16, textColor=PURPLE,  spaceBefore=14, spaceAfter=6, fontName="Helvetica-Bold")
    h2_style     = _style("H2",       fontSize=12, textColor=BLUE,    spaceBefore=10, spaceAfter=4, fontName="Helvetica-Bold")
    h3_style     = _style("H3",       fontSize=10, textColor=PURPLE,  spaceBefore=8,  spaceAfter=3, fontName="Helvetica-Bold")
    body_style   = _style("Body",     fontSize=9,  textColor=LIGHT,   spaceAfter=4,  fontName="Helvetica", leading=14, alignment=TA_JUSTIFY)
    muted_style  = _style("Muted",    fontSize=8,  textColor=MUTED,   spaceAfter=2,  fontName="Helvetica")
    bullet_style = _style("Bullet",   fontSize=9,  textColor=LIGHT,   spaceAfter=2,  fontName="Helvetica", leftIndent=14)
    label_style  = _style("Label",    fontSize=7,  textColor=PURPLE,  spaceAfter=1,  fontName="Helvetica-Bold")
    footer_style = _style("Footer",   fontSize=7,  textColor=MUTED,   alignment=TA_CENTER)

    story = []

    # Cover page
    story.append(Spacer(1, 30 * mm))
    story.append(HRFlowable(width="60%", thickness=2, color=PURPLE, spaceAfter=8 * mm))
    story.append(Paragraph("AI JURY", _style("CoverTitle", fontSize=36, textColor=PURPLE, fontName="Helvetica-Bold", alignment=TA_CENTER)))
    story.append(Paragraph("Multi-Agent Deliberation Report", _style("CoverSub", fontSize=14, textColor=MUTED, alignment=TA_CENTER)))
    story.append(HRFlowable(width="60%", thickness=2, color=PURPLE, spaceAfter=8 * mm))
    story.append(Spacer(1, 10 * mm))

    # Query on cover
    query_table = Table(
        [[Paragraph(prompt, body_style)]],
        colWidths=["100%"],
    )
    query_table.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, -1), colors.HexColor("#8b5cf610")),
        ("BOX",          (0, 0), (-1, -1), 0.5, PURPLE),
        ("LEFTPADDING",  (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING",   (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 8),
    ]))
    story.append(query_table)
    story.append(Spacer(1, 8 * mm))

    # Confidence Score
    conf_color = GREEN if confidence_score >= 75 else (AMBER if confidence_score >= 50 else RED)
    conf_table = Table(
        [[
            Paragraph("CONFIDENCE SCORE", _style("CL", fontSize=8, textColor=MUTED, fontName="Helvetica-Bold")),
            Paragraph(f"{confidence_score}%", _style("CV", fontSize=20, textColor=conf_color, fontName="Helvetica-Bold", alignment=TA_CENTER)),
        ]],
        colWidths=["80%", "20%"],
    )
    conf_table.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (-1, -1), SURFACE),
        ("BOX",         (0, 0), (-1, -1), 0.5, BORDER),
        ("VALIGN",      (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(conf_table)

    story.append(Spacer(1, 10 * mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER, spaceAfter=6 * mm))

    # Executive Summary
    exec_summary = report_data.get("executive_summary", "")
    if exec_summary:
        story.append(Paragraph("Executive Summary", h1_style))
        story.append(Paragraph(exec_summary, body_style))
        story.append(Spacer(1, 4 * mm))

    # Key Findings
    findings = report_data.get("key_findings", [])
    if findings:
        story.append(Paragraph("Key Findings", h1_style))
        for f in findings:
            story.append(Paragraph(f"  {f}", bullet_style))
        story.append(Spacer(1, 4 * mm))

    # Recommendations
    recs = report_data.get("recommendations", [])
    if recs:
        story.append(Paragraph("Recommendations", h1_style))
        for r in recs:
            story.append(Paragraph(f"  {r}", bullet_style))
        story.append(Spacer(1, 4 * mm))

    # Final Answer
    story.append(Paragraph("Final Answer", h1_style))
    for line in final_answer.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 2 * mm))
        elif line.startswith("### "):
            story.append(Paragraph(line[4:], h3_style))
        elif line.startswith("## "):
            story.append(Paragraph(line[3:], h2_style))
        elif line.startswith("# "):
            story.append(Paragraph(line[2:], h2_style))
        elif line.startswith("- ") or line.startswith("* "):
            story.append(Paragraph(f"  {line[2:]}", bullet_style))
        elif line.startswith("```"):
            pass
        else:
            story.append(Paragraph(line, body_style))
    story.append(Spacer(1, 4 * mm))

    # Claim Analysis
    if consensus_claims or disputed_claims:
        story.append(Paragraph("Claim Analysis", h1_style))
        if consensus_claims:
            story.append(Paragraph("Consensus Claims", h2_style))
            for c in consensus_claims[:8]:
                claim_text = c.get("claim", "") if isinstance(c, dict) else str(c)
                story.append(Paragraph(f"  {claim_text}", bullet_style))
            story.append(Spacer(1, 3 * mm))
        if disputed_claims:
            story.append(Paragraph("Disputed Claims", h2_style))
            for d in disputed_claims[:5]:
                claim_text = d.get("claim", "") if isinstance(d, dict) else str(d)
                story.append(Paragraph(f"  {claim_text}", bullet_style))
            story.append(Spacer(1, 4 * mm))

    # Agent Deliberation Transcript
    if debate_turns:
        story.append(Paragraph("Agent Deliberation Transcript", h1_style))
        for turn in debate_turns:
            t = turn if isinstance(turn, dict) else turn.dict()
            speaker = t.get("speaker_persona", "Agent")
            target  = t.get("target_persona", "")
            arg     = t.get("argument", "")
            ev      = t.get("evidence", "")
            header  = f"Turn {t.get('turn_number', '')}: {speaker}" + (f" -> {target}" if target else "")
            story.append(Paragraph(header, h2_style))
            story.append(Paragraph(arg, body_style))
            if ev:
                story.append(Paragraph(f"Evidence: {ev[:200]}", muted_style))
            story.append(Spacer(1, 2 * mm))

    # Footer
    story.append(Spacer(1, 6 * mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER, spaceAfter=3 * mm))
    story.append(Paragraph(
        f"Generated by AI Jury 7-Agent LangGraph Pipeline | {datetime.now().strftime('%Y')}",
        footer_style
    ))

    doc.build(story)
    return buffer.getvalue()


# ═══════════════════════════════════════════════════════════════════════════════
# Email Dispatch
# ═══════════════════════════════════════════════════════════════════════════════

async def compose_and_send_email(
    recipient_email: str,
    prompt: str,
    final_answer: str,
    report_data: dict,
    confidence_score: int,
    debate_turns: list = None,
    consensus_claims: list = None,
    disputed_claims: list = None,
) -> tuple:
    """
    Agent 7 Email Dispatch Agent.
    1. Generates a professional PDF report.
    2. Composes an LLM-written email body.
    3. Attaches the PDF and sends via SMTP.
    Returns (success, message).
    """
    debate_turns     = debate_turns or []
    consensus_claims = consensus_claims or []
    disputed_claims  = disputed_claims or []

    # Step 1: Generate PDF
    try:
        pdf_bytes = _build_pdf(
            prompt=prompt,
            final_answer=final_answer,
            report_data=report_data,
            confidence_score=confidence_score,
            debate_turns=debate_turns,
            consensus_claims=consensus_claims,
            disputed_claims=disputed_claims,
        )
    except Exception as e:
        return False, f"PDF generation failed: {str(e)}"

    # Step 2: LLM composes email
    persona = AGENT_PERSONAS["email_agent"]
    compose_prompt = (
        f"User's question: {prompt}\n\n"
        f"Report title: {report_data.get('title', 'AI Jury Report')}\n"
        f"Executive summary: {report_data.get('executive_summary', '')[:300]}\n"
        f"Confidence score: {confidence_score}%\n\n"
        f"Write a professional, concise email to deliver this AI Jury PDF report. "
        f"Mention the PDF is attached. Return JSON with 'subject' and 'body' keys only."
    )
    raw = await query_llm(persona["model"], compose_prompt, persona["system_instruction"], "json")

    try:
        cleaned = raw.strip().lstrip("```json").lstrip("```").rstrip("```").strip()
        email_data = json.loads(cleaned)
        subject    = email_data.get("subject", f"AI Jury Report {prompt[:50]}")
        body_plain = email_data.get("body", "Please find your AI Jury analysis report attached as a PDF.")
    except Exception:
        subject    = f"AI Jury Report {datetime.now().strftime('%B %d, %Y')}"
        body_plain = (
            f"Hi,\n\nYour AI Jury analysis for the query:\n\"{prompt}\"\n\n"
            f"Confidence Score: {confidence_score}%\n\n"
            f"Please find the full structured report attached as a PDF.\n\n"
            f"- AI Jury 7-Agent Deliberation Pipeline"
        )

    # Step 3: Build HTML email body
    html_body = f"""<html>
<body style="background:#09090b;font-family:Arial,sans-serif;padding:32px;color:#f4f4f5;margin:0">
  <div style="max-width:640px;margin:0 auto;background:#18181b;border-radius:16px;padding:32px;border:1px solid #27272a">
    <div style="display:flex;align-items:center;gap:14px;margin-bottom:28px">
      <div style="width:52px;height:52px;background:linear-gradient(135deg,#8b5cf6,#3b82f6);border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:26px;flex-shrink:0">⚖️</div>
      <div>
        <h1 style="margin:0;font-size:20px;font-weight:700;color:#f4f4f5">AI Jury Report</h1>
        <p style="margin:2px 0 0;font-size:12px;color:#71717a">{datetime.now().strftime('%B %d, %Y at %H:%M')}</p>
      </div>
    </div>
    <div style="background:#8b5cf615;border:1px solid #8b5cf640;border-radius:10px;padding:14px 16px;margin-bottom:20px">
      <p style="margin:0 0 4px;font-size:11px;font-weight:700;color:#a78bfa">YOUR QUERY</p>
      <p style="margin:0;font-size:14px;color:#f4f4f5">{prompt}</p>
    </div>
    <div style="background:#10b98115;border:1px solid #10b98140;border-radius:10px;padding:14px 16px;margin-bottom:20px;display:flex;justify-content:space-between;align-items:center">
      <p style="margin:0;font-size:11px;font-weight:700;color:#34d399">CONFIDENCE SCORE</p>
      <span style="font-size:28px;font-weight:800;color:#10b981">{confidence_score}%</span>
    </div>
    <p style="font-size:13px;color:#a1a1aa;line-height:1.7;margin:0 0 20px">{report_data.get('executive_summary', '')}</p>
    <div style="background:#3b82f615;border:1px solid #3b82f640;border-radius:10px;padding:14px 16px;margin-bottom:24px">
      <p style="margin:0;font-size:13px;color:#93c5fd">The full structured report with agent deliberation transcript and claim analysis is attached as a <strong>PDF</strong>.</p>
    </div>
    <div style="border-top:1px solid #27272a;padding-top:16px;text-align:center">
      <p style="margin:0;font-size:11px;color:#52525b">Generated by AI Jury 7-Agent LangGraph Pipeline | {datetime.now().strftime('%Y')}</p>
    </div>
  </div>
</body></html>"""

    # Step 4: Send via SMTP (use saved config if available, fall back to env vars)
    saved_config = get_email_config()
    if saved_config and saved_config.smtp_user and saved_config.smtp_pass:
        smtp_host = saved_config.smtp_host
        smtp_port = saved_config.smtp_port
        smtp_user = saved_config.smtp_user
        smtp_pass = saved_config.smtp_pass
        sender_name = saved_config.sender_name
        use_tls = saved_config.use_tls
    else:
        smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
        smtp_port = int(os.getenv("SMTP_PORT", "587"))
        smtp_user = os.getenv("SMTP_USER", "")
        smtp_pass = os.getenv("SMTP_PASS", "")
        sender_name = "AI Jury"
        use_tls = True

    if not smtp_user or not smtp_pass:
        return False, "SMTP credentials not configured. Configure them via Email Settings in the sidebar or add SMTP_USER and SMTP_PASS to your .env file."

    try:
        msg = MIMEMultipart("mixed")
        msg["Subject"] = subject
        msg["From"]    = f"{sender_name} <{smtp_user}>"
        msg["To"]      = recipient_email

        alt = MIMEMultipart("alternative")
        alt.attach(MIMEText(body_plain, "plain"))
        alt.attach(MIMEText(html_body, "html"))
        msg.attach(alt)

        pdf_part = MIMEBase("application", "pdf")
        pdf_part.set_payload(pdf_bytes)
        encoders.encode_base64(pdf_part)
        safe_name = "".join(c if c.isalnum() or c in " _-" else "_" for c in prompt[:40]).strip()
        pdf_part.add_header("Content-Disposition", "attachment", filename=f"AI_Jury_Report_{safe_name}.pdf")
        msg.attach(pdf_part)

        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            if use_tls:
                server.starttls()
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, recipient_email, msg.as_string())

        return True, f"PDF report successfully sent to {recipient_email}"

    except Exception as e:
        return False, f"Email send failed: {str(e)}"

